# available directory themes:
# spearmint, peppermint, hemingway, brookmint
theme = 'peppermint'

[general]
title = "Proof of Worth"
logo = ""
iconLogo = "tabler:mood-bitcoin"

[general.seo]
name = "Proof of Worth"
description = "Products these days are often of low quality. We call them Fiat Products. This site lists products that are outstanding and give us a glimpse of what every product would be like in an Bitcoin Standard."
url = "https://proof-of-work-netlify.app"

[directoryData.source]
name = "json"    # default, mock, sheets, json
links = "normal"

[directoryData.tagPages]
title = "{0} products"

[directoryData.search]
placeholder = "Search among {0} products of this directory :)"

[[directoryData.tags]]
key = "breathing"
name = "Breathing"
color = "blue"
emoji = "👃"
description = "Breathing techniques are a popular feature in meditation apps."

[[directoryData.tags]]
key = "sleep"
name = "Sleep"
color = "green"
emoji = "💤"
description = "Some apps include music that slowly goes away to help you sleep better and rest."

[[directoryData.tags]]
key = "meditation"
name = "Meditation"
color = "purple"
emoji = "🧘‍♂️"
description = "A meditation for your life. It's a great way to relax and clear your mind. It's also a great way to improve your sleep."

[[directoryData.tags]]
key = "yoga"
name = "Yoga"
color = "purple"
emoji = "🧘‍♂️"
description = "A yoga for your life."

[[directoryData.tags]]
key = "timer"
name = "Timer"
color = "green"
emoji = "⏰"
description = "Timers can be used to track how much you meditate."

[header.banner]
show = true
text = "Feedback here"
link = "https://x.com/feinripp"
brandText = "Proof of Worth is just getting started"

[header.navbar]
colorModeSelector = true

[[header.navbar.links]]
name = "Blog"
href = "/blog"

[[header.navbar.links]]
name = "Analytics"
href = "https://us.posthog.com/shared/vHlGCcSqPjGH4r_QijaXSETtmN9J-g"
target = "_blank"

[header.actionButton]
text = "Submit a product (coming soon)"
href = "https://proof-of-work-netlify.app"

[footer]
description = "Best directory for my niche."

[footer.socials.x]
link = "https://x.com/mark_bruderer"

[footer.socials.youtube]
link = "https://www.youtube.com/@mark_hacks"
